Repository rpminspect/rpminspect, pull requests merged in 2022-09, with the labels that each got.

#866 Update the TODO file
  TODO
Labels: docs

#872 Add firefox into baseline testing.
  utils/gate.sh
Labels: testing

#873 [lib] Change licensdb to a string_list_t in struct rpminspect
  include/types.h
  lib/debug.c
  lib/free.c
  lib/init.c
  lib/inspect_license.c
Labels: enhancement

#874 [lib] Support multiple license db files in the config file
  data/generic.yaml
  include/init.h
  include/meson.build
  lib/init.c
Labels: enhancement
